eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://BMDISCOVERY:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          #Enabled in true create routes based on services registered with a DiscoveryClient
          enabled: false
    config:
      discovery:
        enabled: true
        service-id: BMCONFIGURATION
      failFast: true
  profiles:
    #Don't delete this property because does not work -Dspring.profiles.active=docker in docker-compouse.yml
    active: docker
  application:
    name: BMGATEWAY
api:
  empleado:
    version: v1
  horario:
    version: v1
  nomina:
    version: v1

# Enable the gateway endpoints to get by example the routes (http://localhost:5555/actuator/gateway/routes/)
management:
  endpoint:
    gateway:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info,refresh

info:
  business-manager-gateway:
    name: Business Manager Gateway
    description: This is SpringCloudGateway server for business manager
    version: 1.0