eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://BM-DISCOVERY:8761/eureka}
spring:
  datasource:
    url: jdbc:postgresql://BM-DB-EMPLEADO:5432/postgres
    username: postgres
    password: postgres
  profiles:
    #Don't delete this property because does not work -Dspring.profiles.active=docker in docker-compouse.yml
    active: docker
  application:
    name: BM_EMPLEADO
  cloud:
    config:
      discovery:
        enabled: true
        service-id: BM_CONFIGURATION
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate

# Expose health and info endpoints to be consumed in web
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  business-manager-empleado:
    name: Business Manager Empleado
    description: This application supports the administration of the employees of B&C company
    version: 1.0