eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://BMDISCOVERY:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  datasource:
    url: jdbc:postgresql://BMDBEMPLEADO:5432/postgres
    username: postgres
    password: postgres
  profiles:
    #Don't delete this property because does not work -Dspring.profiles.active=docker in docker-compouse.yml
    active: docker
  application:
    name: BMEMPLEADO
  cloud:
    config:
      discovery:
        enabled: true
        service-id: BMCONFIGURATION
      failFast: true
    stream:
      kafka:
        binder:
          brokers: BMKAFKA:9092
      bindings:
        empleados-out:
          destination: empleadosTopic
          contentType: application/json
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate

# Expose health and info endpoints to be consumed in web
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  business-manager-empleado:
    name: Business Manager Empleado
    description: This application supports the administration of the employees of B&C company
    version: 1.0

api:
  empleado:
    version: v1
    path: empleado