eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 5555

spring:
  cloud:
    gateway:
      discovery:
        enabled: true
        locator:
          #Enabled create routes based on services registered with a DiscoveryClient
          enabled: true
    config:
      discovery:
        enabled: true
        service-id: BM_CONFIGURATION

# Enable the gateway endpoints to get by example the routes (http://localhost:5555/actuator/gateway/routes/)
management:
  endpoint:
    gateway:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info

info:
  business-manager-gateway:
    name: Business Manager Gateway
    description: This is SpringCloudGateway server for business manager
    version: 1.0